version: '3.8'

volumes:
  dbdata:
    driver: local

services:
  db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: harvester
      POSTGRES_PASSWORD: harvester
      POSTGRES_DB: harvester_development
    volumes:
      - dbdata:/var/lib/postgresql/data/pgdata
